name: example
description: flutter video example
version: 1.0.1+2
publish_to: "none"

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_simple_video_player:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
