name: flutter_simple_video_player
description: flutter simple video player
version: 0.1.0
author: ruihuan <ruihuancao@gmail.com>
homepage: https://github.com/ruihuancao/flutter_page_video.git

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.1.6
  screen: ^0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
